openapi: 3.0.0
info:
  title: Dishes API
  version: 1.0.0
  description: A simple Dishes API

paths:
  /categories:
    get:
      summary: List all categories
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Category'
    post:
      summary: Create a new category
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CategoryInput'
      responses:
        '201':
          description: Category created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Category'
        '400':
          description: Bad request
  /categories/{id}:
    put:
      summary: Update a category
      parameters:
        - in: path
          name: id
          required: true
          description: ID of the category to update
          schema:
            type: integer
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CategoryInput'
      responses:
        '200':
          description: Category updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Category'
        '400':
          description: Bad request
        '404':
          description: Category not found
    delete:
      summary: Delete a category
      parameters:
        - in: path
          name: id
          required: true
          description: ID of the category to delete
          schema:
            type: integer
      responses:
        '204':
          description: Category deleted successfully
        '404':
          description: Category not found

components:
  schemas:
    Category:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
    CategoryInput:
      type: object
      required:
        - name
      properties:
        name:
          type: string