openapi: 3.0.0
info:
  title: Dishes API
  version: 1.0.0
  description: A simple Dishes API

paths:
  /countries:
    get:
      summary: List all countries
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Country'
    post:
      summary: Create a new country
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CountryInput'
      responses:
        '201':
          description: Country created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Country'
        '400':
          description: Bad request
  /countries/{id}:
    put:
      summary: Update a country
      parameters:
        - in: path
          name: id
          required: true
          description: ID of the country to update
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CountryInput'
      responses:
        '200':
          description: Country updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Country'
        '400':
          description: Bad request
        '404':
          description: Country not found
    delete:
      summary: Delete a country
      parameters:
        - in: path
          name: id
          required: true
          description: ID of the country to delete
          schema:
            type: string
      responses:
        '204':
          description: Country deleted successfully
        '404':
          description: Country not found

components:
  schemas:
    Country:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
    CountryInput: # Input schema for POST /countries
      type: object
      required:
        - name
      properties:
        name:
          type: string