openapi: 3.0.0
info:
  title: Dishes API
  version: 1.0.0
  description: A simple Dishes API

paths:
  /countries:
    get:
      summary: List all countries
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Country'
    post:
      summary: Create a new country
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CountryInput'
      responses:
        '201':
          description: Country created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Country'
        '400':
          description: Bad request

components:
  schemas:
    Country:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
    CountryInput: # Input schema for POST /countries
      type: object
      required:
        - name
      properties:
        name:
          type: string