
openapi: 3.0.0
info:
  title: Dishes API
  version: 1.0.0
  description: A simple Dishes API

components: 
  schemas:
    Category: 
      type: object
    Country: 
      type: object
    Ingredient: 
      type: object
    Dish: 
      type: object
