openapi: 3.0.0
info:
  title: Dishes API
  version: 1.0.0
  description: A simple Dishes API

paths:
  /ingredients:
    get:
      summary: List all ingredients
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Ingredient'
    post:
      summary: Create a new ingredient
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/IngredientInput'
      responses:
        '201':
          description: Ingredient created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Ingredient'
        '400':
          description: Bad request
    put:
      summary: Update an ingredient
      parameters:
        - in: path
          name: id
          schema:
            type: string 
          required: true
          description: ID of the ingredient
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/IngredientInput' 
      responses:
        '200':
          description: Ingredient updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Ingredient'
        '400':
          description: Bad request
        '404':
          description: Ingredient not found
    delete:
      summary: Delete an ingredient
      parameters:
        - in: path
          name: id
          schema:
            type: string 
          required: true
          description: ID of the ingredient
      responses:
        '204':
          description: Ingredient deleted successfully
        '404':
          description: Ingredient not found

components:
  schemas:
    Ingredient:
      type: object
      properties:
        id:
          type: string 
        name:
          type: string
    IngredientInput:
      type: object
      required:
        - name
      properties:
        name:
          type: string